### ISSUE TITLE
GPU backend does not work in fit()

### ISSUE THREAD

**Issue by mengqvist** [ElArkk/jax-unirep#78]
I'm running your evotuning example code found here: https://github.com/ElArkk/jax-unirep/blob/master/examples/evotuning.py

When switching the backend variable to 'gpu' the script fails.

```
~/miniconda3/envs/pt/lib/python3.8/site-packages/jaxlib/xla_client.py in get_local_backend(name)
    146       return backends[name]
    147     except KeyError:
--> 148       raise RuntimeError('Unknown backend {}'.format(name))
    149 
    150   return list(backends.values())[-1]

RuntimeError: Unknown backend gpu
```

Perhaps it is not recognizing my GPU?

**Comment by ericmjl** [comment]
Do you have JAX GPU installed? The installation instructions are on JAX’s docs; I think we need to update our docs with a link to there.

**Comment by mengqvist** [comment]
Ah yes! That was indeed the problem. Jax now correctly detects the gpu.
```
>>> from jax.lib import xla_bridge
>>> print(xla_bridge.get_backend().platform)
gpu
```

However, now I get a different error from jax-unirep. The error below appears when I load your library.
```
from jax_unirep import evotune, fit
from jax_unirep.utils import dump_params
```

It is strange that it complains about the xla_bridge when jax clearly detects it. 

```
Kernel started: 366906d2-06eb-4040-bdb1-1497c9291208, name: python3
2020-09-28 14:44:21.418537: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2020-09-28 14:44:21.418583: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2020-09-28 14:44:21.418606: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2020-09-28 14:44:21.418623: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   /usr/local/cuda-10.1
2020-09-28 14:44:21.418640: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2020-09-28 14:44:21.418656: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
```

It clearly looks in the folder cuda-10.1, but I have cuda-10.2. I have attempted to set the XLA_FLAGS variable but this does not help.

**Comment by mengqvist** [comment]
Update: I created a hyperlink from cuda-10.2 to a folder named cuda-10.1 and now everything works fine. Seems like a very fragile solution though.

**Comment by ericmjl** [comment]
It is indeed. We're struggling with the same problems, for example, with running evotuning in a GPU-enabled container. 

From what I've experienced, installing the cudatoolkit in an environment helps one more sanely figure out where to set the XLA flags, though it doesn't get around the issue of fragile paths. 

Btw, keep your eyes peeled for the length 256 and length 50 repping model functions. I've found the 1900-long one quite challenging to evotune because of the length, requiring small batch sizes and hence very long training times. So out of necessity, we'll be putting in the smaller models for global retraining.

**Comment by ericmjl** [comment]
@mengqvist looking at your setup, I just remembered it's possible to install JAX on GPU pre-compiled to target CUDA 10.2. Perhaps that might solve the fragile path issues for you? (XLA is statically linked against one path, `/usr/local/cuda-<version>`, which is not good in my view, but that's how it is.)

**Comment by mengqvist** [comment]
Thanks @ericmjl ! I will give that solution a try.
